### ISSUE TITLE
Problem with font-awesome git submodule

### ISSUE THREAD

**Issue by writeson** [derme302/triple-hyde#15]
Hi,

I'm new to Hugo and I'm trying to use it to build a blog hosted on Github and deployed with Netlify. When I try to deploy using Netlify the deploy log shows this error:

```
5:36:27 PM: ERROR TOCSS: failed to transform "/scss/triple-hyde.scss" (text/x-scss): "/opt/build/repo/themes/triple-hyde/assets/scss/triple-hyde.scss:3:1": File to import not found or unreadable: font-awesome/assets/stylesheets/font-awesome.
5:36:27 PM: Total in 28 ms
5:36:27 PM: Error: error building site: TOCSS: failed to transform "/scss/triple-hyde.scss" (text/x-scss): "/opt/build/repo/themes/triple-hyde/assets/scss/triple-hyde.scss:3:1": File to import not found or unreadable: font-awesome/assets/stylesheets/font-awesome.
```

I've tried many things to resolve this (making triple-hyde a git submodule, editing the triple-hyde.scss file directly, adding a build step to the package.json file to copy the files from node_modules into the themes  assets folder, and more), but no change.

At the moment I'm stumped and could use some help/guidance.

Thanks in advance!
Doug

**Comment by derme302** [comment]
Hey Doug,

This is around the font-awesome git submodule in the scss folder. Updating font-awesome to V6 was tricky as they removed their public CDN. 

I've been mulling over a PR on how to fix this, using it as a git submodule was always a temporary solution. I'm not experienced with Netlify so I can't help with the exact deployment issue with why it'd have an issue with the submodule. For your immediate issue you could consider just forking the theme and coping the font-awesome-sass files in, should do the trick.

The long term solution here is to include the icon SVGs directly in the theme like other popular Hugo themes. As this would just make it easier to deploy in general.

**Comment by derme302** [comment]
The font-awesome-sass files exist as a git submodule in the project. Git submodules are a bit of a pain and don't always clone correctly with older versions of git. I think the short term fix would be just to remove the submodule and include them directly with the project.

However, I think this is a pretty important feature for the project so I've already mocked together what switching to SVGs would look like over on the `dev/font-awesome-svg` branch. It is working but still needs some documentation and I'm hoping to merge it once that is done. Let me know if you have any issues deploying that branch on Netlify otherwise I'll consider this resolved once that branch is merged.

**Comment by writeson** [comment]
Hi Chris,

Thanks for the updates to Triple-Hyde, that fixed my Netlify deployment
issue. I've got my site deployed and running:

https://happycanvasandcode.com/

Again, thanks for your help with this!

Doug

**Comment by derme302** [comment]
Wonderful, glad we could get that issue sorted. Site looks great.
